
suggestion = {
    'y': 'yes',
    'h': 'Hii',
    'n': 'no',
    'p': 'please',
    'he': 'help',
    'b': 'bye',
    't': 'thanks',
    'u': 'you',
    'w': 'welcome',
    'g': 'good',
    'gm': 'good morning',
    'gn': 'good night',
    's': 'sorry',
    'ok': 'okay',
    'hv': 'have',
    'gd': 'great day',
    'tc': 'take care',
    'cm': 'come',
    'go': 'go',
    'wt': 'wait',
    'hlp': 'help',
    'idk': "I don't know",
    'wru': 'where are you',
    'il': 'I love you',
    'brb': 'be right back',
    'ty': 'thank you',
    'np': 'no problem',
    'omg': 'oh my god',
    'p': 'please',
    'sry': 'sorry',
    'wyd': 'what are you doing',
    'cu': 'see you',
    'bbl': 'be back later',
    'btw': 'by the way',
    'gtg': 'got to go',
    'rn': 'right now',
    'asl': 'age sex location',
    'k' :'ok',
    'gtk' :'good to know',
    
    
}

